language: node_js
node_js:
  - "stable"
before_install:
    - npm install -g grunt-cli
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update -qq
    - sudo apt-get install chromium-browser -qq
install: npm install
